'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'ES' | 'EN' | 'QU';

export interface LanguageOption {
  code: Language;
  label: string;
  name: string;
}

export const LANGUAGES: LanguageOption[] = [
  { code: 'ES', label: 'ES', name: 'Español' },
  { code: 'EN', label: 'EN', name: 'English' },
  { code: 'QU', label: 'QU', name: 'Runasimi' },
];

export const translations = {
  ES: {
    // Navbar
    'nav.inicio': 'Inicio',
    'nav.turismo': 'Turismo',
    'nav.busquedaAvanzada': 'Búsqueda Avanzada',
    'nav.buscar': 'Buscar',
    'nav.portalNacional': 'Portal Nacional de Turismo',
    'nav.selectLang': 'Idioma / Language',

    // Search Modal
    'search.modalTitle': 'Buscar Recursos Turísticos',
    'search.placeholder': 'Escribe el nombre del destino, departamento, provincia...',
    'search.popular': 'Búsquedas populares:',
    'search.popular1': 'Machu Picchu',
    'search.popular2': 'Lago Titicaca',
    'search.popular3': 'Cañón del Colca',
    'search.popular4': 'Kuelap',
    'search.popular5': 'Huacachina',
    'search.pressEnter': 'Presiona Enter para buscar en el catálogo nacional',
    'search.close': 'Cerrar',
    'search.exploreAll': 'Ver todos los resultados',

    // Home Page - Top Badge & Hero
    'hero.portalOpenData': 'PORTAL DE DATOS ABIERTOS',
    'hero.republicPeru': 'REPÚBLICA DEL PERÚ',
    'hero.title1': 'Descubre los Recursos Turísticos del',
    'hero.titlePeru': 'Perú',
    'hero.subtitle': 'Explora las maravillas arqueológicas, sitios naturales, rutas oficiales y patrimonio de las 25 regiones con datos técnicos verificados en tiempo real.',
    'hero.catNatural': 'Sitios Naturales',
    'hero.catCultural': 'Manifestaciones Culturales',
    'hero.catFolklore': 'Folclore',

    // Home Page - Metrics
    'home.totalResources': 'Total Recursos',
    'home.inventoryNational': 'Inventario Nacional',
    'home.naturalSites': 'Sitios Naturales',
    'home.cat1Natural': 'Categoría 1 (Natural)',
    'home.culturalHeritage': 'Patrimonio Cultural',
    'home.cat2Cultural': 'Categoría 2 (Cultural)',
    'home.folkloreTraditions': 'Folclore & Tradiciones',
    'home.cat3Folklore': 'Categoría 3 (Folclore)',
    'home.metricAttractions': 'Atractivos',
    'home.metricRegions': 'Regiones',
    'home.metricOpen': 'Abierto',

    // Home Page - Featured Catalog
    'home.featuredBadge': 'Inventario Nacional • Registros Seleccionados',
    'home.featuredTitle': 'Recursos Turísticos Destacados',
    'home.featuredSubtitle': 'Fichas técnicas oficiales georreferenciadas con metadatos descriptivos y de ubicación.',
    'home.viewAllCatalog': 'Ver Catálogo Completo',
    'home.verifiedLocation': 'Ubicación Verificada',
    'home.viewTechnicalSheet': 'Ver Ficha Técnica',
    'home.viewFullDetail': 'Ver detalle completo',

    // Home Page - Geoportal IDE
    'home.ideBadge': 'Infraestructura de Datos Espaciales (IDE)',
    'home.geoportalTitle': 'Geoportal de Atractivos Turísticos',
    'home.geoportalSubtitle': 'Visualización espacial de puntos georreferenciados en el sistema de coordenadas WGS-84 (EPSG:4326).',
    'home.activeInGeoportal': 'Registro Activo en Geoportal',
    'home.category': 'Categoría',
    'home.provinceDistrict': 'Provincia / Distrito',
    'home.latitude': 'Latitud (WGS-84)',
    'home.longitude': 'Longitud (WGS-84)',
    'home.selectMarkerMap': 'Selecciona un marcador en el mapa para inspeccionar sus coordenadas y metadatos.',
    'home.viewFullTechSheet': 'Ver Ficha Técnica Completa',

    // Home Page - Banner CTA
    'home.openDbBadge': 'Base de Datos Abierta',
    'home.bannerTitle': 'Consulte el Catálogo Nacional de Turismo',
    'home.bannerDesc': 'Filtre por departamentos, provincias, categorías y actividades turísticas con datos normalizados, coordenadas geodésicas y fichas técnicas oficiales.',
    'home.exploreCatalog': 'Explorar Catálogo',
    'home.viewGeoportal': 'Ver Geoportal',
    'home.advantagesBadge': 'Ventajas de la Plataforma',
    'home.whyChoose': '¿Por Qué Elegir',
    'home.whyChooseDesc': 'Somos el visualizador de datos abiertos y georreferenciación turística más intuitivo del país. Conectamos a ciudadanos, viajeros, estudiantes, investigadores y operadores con información 100% oficial de manera rápida, limpia y sin fricciones.',
    'home.feat1Title': 'Datos 100% Oficiales',
    'home.feat1Desc': 'Información técnica y fotográfica sincronizada directamente con el inventario nacional sin manipulación.',
    'home.feat2Title': 'Acceso Libre y Seguro',
    'home.feat2Desc': 'Consulta ilimitada sin registros obligatorios, sin recopilación de datos personales ni rastreo publicitario.',
    'home.feat3Title': 'Rutas e Itinerarios',
    'home.feat3Desc': 'Detalle paso a paso para llegar a cada destino con medios de transporte, tipos de vía y tiempos estimados.',
    'home.feat4Title': 'Búsqueda Inteligente',
    'home.feat4Desc': 'Filtros dinámicos por región, categoría, actividad o código único de ficha para encontrar tu destino al instante.',
    'home.ctaTitle': '¿Listo para Explorar el Perú?',
    'home.ctaDesc': 'Accede al catálogo completo de OpenData con más de 5,000 atractivos turísticos georreferenciados, fotos oficiales y videos en vivo.',
    'home.ctaBtn': 'Explorar el Catálogo Ahora',

    // Map
    'map.loading': 'Cargando Geoportal OpenStreetMap...',
    'map.loadingPapa': 'Cargando Geoportal interactivo...',

    // Turismo Page
    'turismo.badge': 'CATÁLOGO NACIONAL • INVENTARIO TURÍSTICO',
    'turismo.heroTitle': 'Explorador del Patrimonio',
    'turismo.heroHighlight': 'Turístico del Perú',
    'turismo.heroSubtitle': 'Consulte más de 2,290 recursos georreferenciados con metadatos oficiales, rutas de acceso y coordenadas espaciales.',
    'turismo.title': 'Catálogo de',
    'turismo.titleHighlight': 'Recursos Turísticos',
    'turismo.subtitle': 'Consulta, filtra y localiza más de 5,000 atractivos georreferenciados en todo el territorio peruano.',
    'turismo.searchPlaceholder': 'Buscar por nombre o palabra clave (ej: Machu Picchu, Colca, Lago Titicaca...)',
    'turismo.btnAdvanced': 'Avanzado (Código)',
    'turismo.btnSearch': 'Buscar',
    'turismo.filterRegion': 'Región / Departamento',
    'turismo.allRegions': 'Todas las regiones',
    'turismo.filterCategory': 'Categoría',
    'turismo.allCategories': 'Todas las categorías',
    'turismo.filterActivity': 'Actividad',
    'turismo.allActivities': 'Todas las actividades',
    'turismo.typesRegistered': 'tipos registrados',
    'turismo.official': 'Oficial',
    'turismo.advancedTitle': 'Búsqueda Avanzada por Código de Ficha',
    'turismo.advancedPlaceholder': 'Ingresa el número de ficha (ej: 62, 154, 820, 7482...)',
    'turismo.advancedDesc': 'Búsqueda directa por el identificador numérico único registrado en el inventario.',
    'turismo.removeCode': 'Quitar código',
    'turismo.filtersApplied': 'Filtros aplicados en la búsqueda actual',
    'turismo.filtersReady': 'Filtros seleccionados listos para buscar',
    'turismo.filtersActive': 'Filtros activos:',
    'turismo.textFilter': 'Texto',
    'turismo.deptFilter': 'Región',
    'turismo.categoryFilter': 'Categoría',
    'turismo.activityFilter': 'Actividad',
    'turismo.codeFilter': 'Ficha',
    'turismo.clearFilters': 'Limpiar todos los filtros',
    'turismo.sectionBadge': 'Exploración Abierta',
    'turismo.allResources': 'Todos los Recursos Turísticos Registrados',
    'turismo.resourcesIn': 'Recursos en',
    'turismo.codeSearch': 'Ficha con Código N°',
    'turismo.resultsFor': 'Resultados para',
    'turismo.foundCount': 'atractivos encontrados',
    'turismo.reset': 'Restablecer',
    'turismo.loading': 'Consultando base de datos abierta...',
    'turismo.noResults': 'No se encontraron atractivos turísticos',
    'turismo.noResultsDesc': 'Intenta ajustar tus criterios de búsqueda, cambiar de región o limpiar los filtros aplicados.',
    'turismo.viewSheet': 'Ver ficha del recurso turístico',
    'turismo.inventory': 'Inventario',

    // Ruta del Papa León XIV
    'papa.badge': 'PROGRAMA OFICIAL • 11 AL 16 DE NOVIEMBRE 2026',
    'papa.title': 'Ruta del',
    'papa.titleHighlight': 'Papa León XIV en el Perú',
    'papa.subtitle': 'Georreferenciación oficial del itinerario de actividades, encuentros pastorales y celebraciones masivas por departamento.',
    'papa.searchPlaceholder': 'Buscar por lugar o actividad (ej. Pimentel, Saqsaywaman, Monumental, Las Palmas...)',
    'papa.filterDept': 'Departamento',
    'papa.allDepts': 'Todos los departamentos (6)',
    'papa.filterDate': 'Día / Fecha',
    'papa.allDates': 'Todos los días (6 días)',
    'papa.filterType': 'Tipo de Actividad',
    'papa.allTypes': 'Todos los tipos de eventos',
    'papa.geoportalBadge': 'INFRAESTRUCTURA DE DATOS ESPACIALES (IDE)',
    'papa.geoportalTitle': 'Geoportal de la Ruta Papal',
    'papa.geoportalDesc': 'Visualización interactiva y recorrido secuencial de las actividades pontificias en el mapa nacional.',
    'papa.inspectorTitle': 'Detalle de la Actividad Seleccionada',
    'papa.deptActivities': 'Actividades en {dept}',
    'papa.allDeptActivities': 'Todas las actividades del cronograma',
    'papa.selectToLocate': 'Haz clic en una actividad para ubicarla en el mapa',
    'papa.itineraryTitle': 'Itinerario y Cronograma Oficial',
    'papa.officialSource': 'Fuente Oficial IRTP / Presidencia',
    'papa.activitiesFound': 'actividades encontradas',
    'papa.viewOnMap': 'Centrar en mapa',
    'papa.locatedOnMap': 'Ubicado en mapa',
    'papa.readOfficial': 'Leer comunicado oficial en Gob.pe',
    'papa.massTag': 'Santa Misa Masiva',
    'papa.youthTag': 'Jóvenes / Vigilia',
    'papa.pastoralTag': 'Encuentro Pastoral',
    'papa.travelTag': 'Vuelo / Traslado',
    'papa.officialActivity': 'actividad oficial',
    'papa.officialActivities': 'actividades oficiales',
    'papa.november': 'de Noviembre, 2026',

    // Footer
    'footer.desc': 'Plataforma nacional de datos abiertos para la consulta, georreferenciación y exploración interactiva de los recursos y atractivos turísticos del Perú.',
    'footer.connect': 'Conéctate con Nosotros',
    'footer.nav': 'Navegación',
    'footer.navHome': 'Inicio (Portal Principal)',
    'footer.navTurismo': 'Turismo & Explorador',
    'footer.navMap': 'Mapa de Regiones',
    'footer.navCatalog': 'Catálogo Georreferenciado',
    'footer.dataApi': 'Datos Abiertos & API',
    'footer.transparency': 'Transparencia',
    'footer.terms': 'Términos y Condiciones',
    'footer.privacy': 'Políticas de Privacidad',
    'footer.license': 'Licencia de Datos Abiertos',
    'footer.claims': 'Libro de Reclamaciones',
    'footer.faq': 'Preguntas Frecuentes (FAQ)',
    'footer.rights': 'Repositorio Nacional de Datos de Turismo del Perú',
    'footer.departments': '25 Departamentos',
    'footer.resources': '2,290+ Recursos',
    'footer.open': '100% Abierto',

    // Card
    'card.loadingPhoto': 'Cargando fotografía...',
    'card.noPhoto': 'Sin fotografía digitalizada en ficha',
    'card.recordNum': 'Ficha',
    'card.inventoryTitle': 'Inventario Turístico Nacional',
    'card.touristResource': 'Recurso Turístico',
    'card.themeMuseum': 'Museo y Exposición',
    'card.themeCultural': 'Patrimonio Cultural',
    'card.themeWater': 'Cuerpo de Agua / Costa',
    'card.themeNature': 'Formación Natural',
    'card.themeGeneral': 'Recurso Turístico',

    // Ficha Detail Page
    'ficha.breadcrumbHome': 'Inicio',
    'ficha.breadcrumbTurismo': 'Turismo',
    'ficha.backToCatalog': 'Volver al Catálogo',
    'ficha.sourceFile': 'Ficha Fuente',
    'ficha.loading': 'Cargando información del recurso...',
    'ficha.notFound': 'Esta ficha no existe o ha sido dada de baja del inventario.',
    'ficha.notFoundDesc': 'El recurso solicitado no se encuentra publicado o no está registrado en el inventario.',
    'ficha.exploreOther': 'Explorar otros destinos',
    'ficha.officialPhoto': 'Fotografía del Recurso',
    'ficha.officialGallery': 'Galería de Fotos',
    'ficha.photos': 'fotos',
    'ficha.officialDescription': 'Descripción del Atractivo',
    'ficha.minceturInventory': 'Inventario Nacional',
    'ficha.techSpecs': 'Ficha Técnica',
    'ficha.category': 'Categoría:',
    'ficha.type': 'Tipo:',
    'ficha.subtype': 'Subtipo:',
    'ficha.altitude': 'Altitud:',
    'ficha.notSpecified': 'No especificada',
    'ficha.notSpecifiedMale': 'No especificado',
    'ficha.viewOnMap': 'Ver Ubicación en Mapa',
    'ficha.seasonAndHours': 'Época Propicia y Horarios',
    'ficha.visit': 'Visita',
    'ficha.recommendedSeason': 'Temporada Recomendada',
    'ficha.visitingHours': 'Horario de Visita',
    'ficha.recommendations': 'Recomendaciones',
    'ficha.activitiesInResource': 'Actividades en el Recurso',
    'ficha.howToGet': 'Ruta de Acceso al Recurso (Cómo Llegar)',
    'ficha.howToGetDesc': 'Itinerario registrado tramo por tramo con medios de transporte, tipo de vía y tiempos estimados.',
    'ficha.registeredSections': 'Tramos Registrados',
    'ficha.liveVideo': 'Material Audiovisual (Video en Vivo)',
    'ficha.additionalInfo': 'Información Adicional del Inventario',
    'ficha.fullscreen': 'Ver pantalla completa',
    'ficha.share': 'Compartir',
    'ficha.copied': '¡Copiado!',

    // Pagination
    'pagination.showing': 'Mostrando {start} a {end} de {total} destinos turísticos',
    'pagination.prev': 'Anterior',
    'pagination.next': 'Siguiente',

    // Not Found
    'notFound.title': 'Recurso no encontrado',
    'notFound.desc': 'La página o recurso turístico que está buscando no existe o ha sido reubicado.',
    'notFound.btn': 'Explorar Recursos Turísticos',

    // Privacy Page
    'privacy.title': 'Políticas de Privacidad',
    'privacy.badge': 'Privacidad y Anonimato Garantizado',
    'privacy.heroDesc': 'En OpenData Perú garantizamos un entorno 100% libre, anónimo y seguro. Nuestro único propósito es facilitar la lectura y consulta visual de los datos oficiales públicos del inventario nacional.',
    'privacy.s1Title': 'No Recopilamos Datos Personales',
    'privacy.s1Box': 'Esta plataforma NO solicita, NO almacena, NO procesa y NO recopila ningún tipo de información personal ni datos de contacto de los visitantes.',
    'privacy.s1Desc': 'Puedes navegar libremente, filtrar por departamentos, buscar por categorías, actividades o códigos de ficha sin necesidad de registrarte, iniciar sesión o proporcionar nombres, correos electrónicos, teléfonos ni ubicaciones privadas.',
    'privacy.s2Title': 'Fuente Oficial y Sin Manipulación de Datos',
    'privacy.s2Desc1': 'Toda la información turística presentada proviene exclusivamente de servicios y catálogos de datos abiertos del Estado Peruano:',
    'privacy.s2Desc2': 'Los nombres, descripciones, categorías, departamentos, provincias, distritos, actividades registradas y fotografías se muestran de manera fiel y transparente según el registro oficial, sin alteraciones ni manipulación de su contenido técnico.',
    'privacy.s3Title': 'Objetivo: Máxima Legibilidad y Accesibilidad',
    'privacy.s3Desc': 'El único fin de este portal es brindar una interfaz moderna, ágil, accesible y fácil de interpretar para que turistas, estudiantes, investigadores y ciudadanos puedan explorar el patrimonio turístico nacional de una manera mucho más visual, interactiva y comprensible.',
    'privacy.s4Title': 'Sin Rastreo Comercial ni Publicidad',
    'privacy.s4Desc': 'No utilizamos herramientas de rastreo publicitario invasivas ni comercializamos con el historial de navegación de los usuarios. La experiencia de consulta es limpia, abierta y orientada estrictamente al acceso a datos públicos.',
    'privacy.backCatalog': 'Volver al Catálogo de Turismo',

    // Terms Page
    'terms.title': 'Términos y Condiciones de Uso',
    'terms.badge': 'Transparencia y Uso de Datos Abiertos',
    'terms.heroDesc': 'OpenData Perú es un portal de consulta pública que visualiza la información oficial del Inventario Nacional de Recursos Turísticos del Perú sin manipulación de datos ni recolección de información de los usuarios.',
    'terms.s1Title': 'Origen Oficial de la Información',
    'terms.s1Desc1': 'Todos los datos, fichas técnicas, códigos de registro, ubicaciones departamentales, clasificaciones, descripciones y material fotográfico mostrados en este portal son recopilados directamente desde plataformas de datos abiertos del Estado Peruano.',
    'terms.s1Desc2': 'Las entidades públicas rectoras correspondientes son titulares originales de las bases de datos del Inventario Turístico Nacional del Perú.',
    'terms.s2Title': 'Sin Manipulación de Datos',
    'terms.s2Desc1': 'OpenData Perú actúa como un visualizador de datos abiertos. No alteramos, no modificamos, no editamos y no manipulamos las descripciones técnicas, jerarquías, estados ni coordenadas oficiales registradas en el inventario.',
    'terms.s2Desc2': 'La plataforma preserva íntegramente las coordenadas geodésicas en el sistema WGS-84 y los códigos identificadores de cada ficha técnica.',
    'terms.s3Title': 'Propósito: Mayor Accesibilidad y Visualización',
    'terms.s3Desc': 'La plataforma ha sido desarrollada con la finalidad exclusiva de presentar los datos públicos de una forma más intuitiva, moderna, accesible y rápida para la ciudadanía, investigadores y viajeros:',
    'terms.featSearchTitle': 'Búsqueda Rápida',
    'terms.featSearchDesc': 'Filtros dinámicos por región, categoría, actividad o código único de ficha.',
    'terms.featDesignTitle': 'Diseño Legible',
    'terms.featDesignDesc': 'Estructura visual limpia, tipografía optimizada y soporte para modo claro y oscuro.',
    'terms.featOpenTitle': 'Acceso Abierto',
    'terms.featOpenDesc': 'Libre disponibilidad sin registros obligatorios ni barreras para la consulta.',
    'terms.s4Title': 'Privacidad y Libre Acceso',
    'terms.s4Desc': 'Reiteramos nuestro compromiso de no recolectar, almacenar ni comercializar información personal de los visitantes. La consulta al catálogo es libre y transparente.',
  },
  EN: {
    // Navbar
    'nav.inicio': 'Home',
    'nav.turismo': 'Tourism',
    'nav.busquedaAvanzada': 'Advanced Search',
    'nav.buscar': 'Search',
    'nav.portalNacional': 'National Tourism Open Data Portal',
    'nav.selectLang': 'Language / Idioma',

    // Search Modal
    'search.modalTitle': 'Search Tourist Destinations',
    'search.placeholder': 'Type destination name, region, province...',
    'search.popular': 'Popular searches:',
    'search.popular1': 'Machu Picchu',
    'search.popular2': 'Lake Titicaca',
    'search.popular3': 'Colca Canyon',
    'search.popular4': 'Kuelap',
    'search.popular5': 'Huacachina',
    'search.pressEnter': 'Press Enter to search the national inventory',
    'search.close': 'Close',
    'search.exploreAll': 'View all results',

    // Home Page - Top Badge & Hero
    'hero.portalOpenData': 'OPEN DATA PORTAL',
    'hero.republicPeru': 'REPUBLIC OF PERU',
    'hero.title1': 'Discover the Tourist Destinations of',
    'hero.titlePeru': 'Peru',
    'hero.subtitle': 'Explore archaeological wonders, natural sites, official routes and heritage across 25 regions with real-time verified open data.',
    'hero.catNatural': 'Natural Sites',
    'hero.catCultural': 'Cultural Heritage',
    'hero.catFolklore': 'Folklore',

    // Home Page - Metrics
    'home.totalResources': 'Total Resources',
    'home.inventoryNational': 'National Inventory',
    'home.naturalSites': 'Natural Sites',
    'home.cat1Natural': 'Category 1 (Natural)',
    'home.culturalHeritage': 'Cultural Heritage',
    'home.cat2Cultural': 'Category 2 (Cultural)',
    'home.folkloreTraditions': 'Folklore & Traditions',
    'home.cat3Folklore': 'Category 3 (Folklore)',
    'home.metricAttractions': 'Destinations',
    'home.metricRegions': 'Regions',
    'home.metricOpen': 'Open Data',

    // Home Page - Featured Catalog
    'home.featuredBadge': 'National Inventory • Selected Records',
    'home.featuredTitle': 'Featured Tourist Resources',
    'home.featuredSubtitle': 'Official georeferenced technical sheets with descriptive metadata and spatial coordinates.',
    'home.viewAllCatalog': 'View Full Catalog',
    'home.verifiedLocation': 'Verified Location',
    'home.viewTechnicalSheet': 'View Technical Sheet',
    'home.viewFullDetail': 'View full detail',

    // Home Page - Geoportal IDE
    'home.ideBadge': 'Spatial Data Infrastructure (SDI)',
    'home.geoportalTitle': 'Tourist Attractions Geoportal',
    'home.geoportalSubtitle': 'Spatial visualization of georeferenced coordinates in WGS-84 (EPSG:4326) reference system.',
    'home.activeInGeoportal': 'Active Record on Geoportal',
    'home.category': 'Category',
    'home.provinceDistrict': 'Province / District',
    'home.latitude': 'Latitude (WGS-84)',
    'home.longitude': 'Longitude (WGS-84)',
    'home.selectMarkerMap': 'Select a marker on the map to inspect its coordinates and technical metadata.',
    'home.viewFullTechSheet': 'View Complete Technical Sheet',

    // Home Page - Banner CTA
    'home.openDbBadge': 'Open Database',
    'home.bannerTitle': 'Query the National Tourism Catalog',
    'home.bannerDesc': 'Filter by departments, provinces, categories and tourist activities with normalized data, geodesic coordinates and official technical sheets.',
    'home.exploreCatalog': 'Explore Catalog',
    'home.viewGeoportal': 'View Geoportal',
    'home.advantagesBadge': 'Platform Advantages',
    'home.whyChoose': 'Why Choose',
    'home.whyChooseDesc': 'We are the most intuitive open data and tourism georeferencing viewer in the country. We connect citizens, travelers, students, researchers and tour operators with 100% official data quickly, cleanly and seamlessly.',
    'home.feat1Title': '100% Official Data',
    'home.feat1Desc': 'Technical and photographic information synchronized directly with the national inventory.',
    'home.feat2Title': 'Free & Secure Access',
    'home.feat2Desc': 'Unlimited exploration with no required signup, no personal data collection, and no ad tracking.',
    'home.feat3Title': 'Routes & Itineraries',
    'home.feat3Desc': 'Step-by-step guidance to reach every destination with transport methods, road types and travel times.',
    'home.feat4Title': 'Smart Search',
    'home.feat4Desc': 'Dynamic filters by region, category, activity or unique technical code to find your destination instantly.',
    'home.ctaTitle': 'Ready to Explore Peru?',
    'home.ctaDesc': 'Access the complete OpenData catalog with over 5,000 georeferenced tourist attractions, official photos, and live video.',
    'home.ctaBtn': 'Explore the Catalog Now',

    // Map
    'map.loading': 'Loading OpenStreetMap Geoportal...',
    'map.loadingPapa': 'Loading interactive Geoportal...',

    // Turismo Page
    'turismo.badge': 'NATIONAL CATALOG • TOURISM INVENTORY',
    'turismo.heroTitle': 'Explorer of the Cultural Heritage',
    'turismo.heroHighlight': '& Tourism of Peru',
    'turismo.heroSubtitle': 'Query over 2,290 georeferenced resources with official metadata, access routes, and spatial coordinates.',
    'turismo.title': 'Catalog of',
    'turismo.titleHighlight': 'Tourist Resources',
    'turismo.subtitle': 'Query, filter, and discover more than 5,000 georeferenced attractions throughout Peruvian territory.',
    'turismo.searchPlaceholder': 'Search by name or keyword (e.g., Machu Picchu, Colca, Lake Titicaca...)',
    'turismo.btnAdvanced': 'Advanced (Code)',
    'turismo.btnSearch': 'Search',
    'turismo.filterRegion': 'Region / Department',
    'turismo.allRegions': 'All regions (25)',
    'turismo.filterCategory': 'Category',
    'turismo.allCategories': 'All categories',
    'turismo.filterActivity': 'Activity',
    'turismo.allActivities': 'All activities',
    'turismo.typesRegistered': 'registered types',
    'turismo.official': 'Official',
    'turismo.advancedTitle': 'Advanced Search by Record Code',
    'turismo.advancedPlaceholder': 'Enter record number (e.g., 62, 154, 820, 7482...)',
    'turismo.advancedDesc': 'Direct search using the unique numeric identifier registered in the inventory.',
    'turismo.removeCode': 'Remove code',
    'turismo.filtersApplied': 'Filters applied to current search',
    'turismo.filtersReady': 'Selected filters ready to search',
    'turismo.filtersActive': 'Active filters:',
    'turismo.textFilter': 'Text',
    'turismo.deptFilter': 'Region',
    'turismo.categoryFilter': 'Category',
    'turismo.activityFilter': 'Activity',
    'turismo.codeFilter': 'Record',
    'turismo.clearFilters': 'Clear all filters',
    'turismo.sectionBadge': 'Open Exploration',
    'turismo.allResources': 'All Registered Tourist Resources',
    'turismo.resourcesIn': 'Resources in',
    'turismo.codeSearch': 'Record Code #',
    'turismo.resultsFor': 'Results for',
    'turismo.foundCount': 'attractions found',
    'turismo.reset': 'Reset',
    'turismo.loading': 'Querying open database...',
    'turismo.noResults': 'No tourist attractions found',
    'turismo.noResultsDesc': 'Try adjusting your search criteria, switching region or clearing the applied filters.',
    'turismo.viewSheet': 'View tourist resource sheet',
    'turismo.inventory': 'Inventory',

    // Pope Leo XIV Route
    'papa.badge': 'OFFICIAL PROGRAM • NOVEMBER 11 - 16, 2026',
    'papa.title': 'Route of',
    'papa.titleHighlight': 'Pope Leo XIV in Peru',
    'papa.subtitle': 'Official georeferencing of the itinerary, pastoral encounters, and massive celebrations by department.',
    'papa.searchPlaceholder': 'Search by place or activity (e.g., Pimentel, Saqsaywaman, Monumental, Las Palmas...)',
    'papa.filterDept': 'Department',
    'papa.allDepts': 'All departments (6)',
    'papa.filterDate': 'Day / Date',
    'papa.allDates': 'All days (6 days)',
    'papa.filterType': 'Activity Type',
    'papa.allTypes': 'All event types',
    'papa.geoportalBadge': 'SPATIAL DATA INFRASTRUCTURE (SDI)',
    'papa.geoportalTitle': 'Papal Route Geoportal',
    'papa.geoportalDesc': 'Interactive visualization and sequential mapping of pontifical activities across the national map.',
    'papa.inspectorTitle': 'Selected Activity Details',
    'papa.deptActivities': 'Activities in {dept}',
    'papa.allDeptActivities': 'All scheduled activities',
    'papa.selectToLocate': 'Click on an activity to locate it on the map',
    'papa.itineraryTitle': 'Official Itinerary & Schedule',
    'papa.officialSource': 'Official Source IRTP / Presidency',
    'papa.activitiesFound': 'activities found',
    'papa.viewOnMap': 'Center on map',
    'papa.locatedOnMap': 'Located on map',
    'papa.readOfficial': 'Read official press release on Gob.pe',
    'papa.massTag': 'Massive Mass',
    'papa.youthTag': 'Youth / Vigil',
    'papa.pastoralTag': 'Pastoral Encounter',
    'papa.travelTag': 'Flight / Transfer',
    'papa.officialActivity': 'official activity',
    'papa.officialActivities': 'official activities',
    'papa.november': 'November, 2026',

    // Footer
    'footer.desc': 'National open data platform for interactive query, georeferencing, and exploration of Peru’s tourist resources and attractions.',
    'footer.connect': 'Connect with Us',
    'footer.nav': 'Navigation',
    'footer.navHome': 'Home (Main Portal)',
    'footer.navTurismo': 'Tourism & Explorer',
    'footer.navMap': 'Regions Map',
    'footer.navCatalog': 'Georeferenced Catalog',
    'footer.dataApi': 'Open Data & API',
    'footer.transparency': 'Transparency',
    'footer.terms': 'Terms & Conditions',
    'footer.privacy': 'Privacy Policy',
    'footer.license': 'Open Data License',
    'footer.claims': 'Complaints Book',
    'footer.faq': 'Frequently Asked Questions (FAQ)',
    'footer.rights': 'National Tourism Open Data Repository of Peru',
    'footer.departments': '25 Departments',
    'footer.resources': '2,290+ Resources',
    'footer.open': '100% Open',

    // Card
    'card.loadingPhoto': 'Loading photograph...',
    'card.noPhoto': 'No digitized photo in record',
    'card.recordNum': 'Record',
    'card.inventoryTitle': 'National Tourism Inventory',
    'card.touristResource': 'Tourist Resource',
    'card.themeMuseum': 'Museum & Exhibition',
    'card.themeCultural': 'Cultural Heritage',
    'card.themeWater': 'Water Body / Coast',
    'card.themeNature': 'Natural Formation',
    'card.themeGeneral': 'Tourist Resource',

    // Ficha Detail Page
    'ficha.breadcrumbHome': 'Home',
    'ficha.breadcrumbTurismo': 'Tourism',
    'ficha.backToCatalog': 'Back to Catalog',
    'ficha.sourceFile': 'Source Record',
    'ficha.loading': 'Loading resource data...',
    'ficha.notFound': 'This record does not exist or has been retired from the inventory.',
    'ficha.notFoundDesc': 'The requested resource is not published or registered in the inventory.',
    'ficha.exploreOther': 'Explore other destinations',
    'ficha.officialPhoto': 'Resource Photograph',
    'ficha.officialGallery': 'Photo Gallery',
    'ficha.photos': 'photos',
    'ficha.officialDescription': 'Resource Description',
    'ficha.minceturInventory': 'National Inventory',
    'ficha.techSpecs': 'Technical Sheet',
    'ficha.category': 'Category:',
    'ficha.type': 'Type:',
    'ficha.subtype': 'Subtype:',
    'ficha.altitude': 'Altitude:',
    'ficha.notSpecified': 'Not specified',
    'ficha.notSpecifiedMale': 'Not specified',
    'ficha.viewOnMap': 'View Location on Map',
    'ficha.seasonAndHours': 'Best Season & Visiting Hours',
    'ficha.visit': 'Visit',
    'ficha.recommendedSeason': 'Recommended Season',
    'ficha.visitingHours': 'Visiting Hours',
    'ficha.recommendations': 'Recommendations',
    'ficha.activitiesInResource': 'Activities in Destination',
    'ficha.howToGet': 'Access Route & How to Get There',
    'ficha.howToGetDesc': 'Itinerary recorded section by section with transportation modes, road types and estimated travel times.',
    'ficha.registeredSections': 'Registered Sections',
    'ficha.liveVideo': 'Audiovisual Material (Live Video)',
    'ficha.additionalInfo': 'Additional Information from Inventory',
    'ficha.fullscreen': 'View fullscreen',
    'ficha.share': 'Share',
    'ficha.copied': 'Copied!',

    // Pagination
    'pagination.showing': 'Showing {start} to {end} of {total} tourist destinations',
    'pagination.prev': 'Previous',
    'pagination.next': 'Next',

    // Not Found
    'notFound.title': 'Resource Not Found',
    'notFound.desc': 'The page or tourist resource you are looking for does not exist or has been relocated.',
    'notFound.btn': 'Explore Tourist Resources',

    // Privacy Page
    'privacy.title': 'Privacy Policy',
    'privacy.badge': 'Guaranteed Privacy & Anonymity',
    'privacy.heroDesc': 'At OpenData Peru we guarantee a 100% free, anonymous, and secure environment. Our sole purpose is to facilitate the reading and visual exploration of official public open data.',
    'privacy.s1Title': 'We Do Not Collect Personal Data',
    'privacy.s1Box': 'This platform DOES NOT request, DOES NOT store, DOES NOT process, and DOES NOT collect any personal information or contact details from visitors.',
    'privacy.s1Desc': 'You can browse freely, filter by regions, search by categories, activities, or sheet codes without signing up, logging in, or providing names, emails, phones, or private locations.',
    'privacy.s2Title': 'Official Source & Unaltered Data',
    'privacy.s2Desc1': 'All tourism information presented comes exclusively from open data catalogs and services of the Peruvian State:',
    'privacy.s2Desc2': 'Names, descriptions, categories, regions, provinces, districts, recorded activities, and photographs are displayed faithfully and transparently according to official records, without technical alterations.',
    'privacy.s3Title': 'Objective: Maximum Readability & Accessibility',
    'privacy.s3Desc': 'The sole purpose of this portal is to provide a modern, agile, accessible, and intuitive interface for tourists, students, researchers, and citizens to explore the national tourism heritage.',
    'privacy.s4Title': 'No Commercial Tracking or Advertising',
    'privacy.s4Desc': 'We do not use invasive tracking tools nor do we monetize users browsing history. The browsing experience is clean, open, and strictly focused on public data access.',
    'privacy.backCatalog': 'Back to Tourism Catalog',

    // Terms Page
    'terms.title': 'Terms and Conditions of Use',
    'terms.badge': 'Transparency & Open Data Use',
    'terms.heroDesc': 'OpenData Peru is a public portal visualizing official information from the National Tourism Inventory of Peru without data manipulation or user information collection.',
    'terms.s1Title': 'Official Origin of Information',
    'terms.s1Desc1': 'All data, technical sheets, registry codes, regional locations, classifications, descriptions, and photographs shown on this portal are compiled directly from open data platforms of the Peruvian State.',
    'terms.s1Desc2': 'The corresponding governing public entities are the original owners of the National Tourism Inventory databases of Peru.',
    'terms.s2Title': 'No Data Manipulation',
    'terms.s2Desc1': 'OpenData Peru acts as an open data visualizer. We do not alter, modify, edit, or manipulate technical descriptions, hierarchies, statuses, or official coordinates.',
    'terms.s2Desc2': 'The platform fully preserves geodesic coordinates in the WGS-84 system and unique identifier codes for each technical sheet.',
    'terms.s3Title': 'Purpose: Enhanced Accessibility & Visualization',
    'terms.s3Desc': 'The platform was developed solely to present public data in an intuitive, modern, accessible, and fast way for citizens, researchers, and travelers:',
    'terms.featSearchTitle': 'Fast Search',
    'terms.featSearchDesc': 'Dynamic filters by region, category, activity, or unique sheet code.',
    'terms.featDesignTitle': 'Readable Design',
    'terms.featDesignDesc': 'Clean visual structure, optimized typography, and support for light and dark modes.',
    'terms.featOpenTitle': 'Open Access',
    'terms.featOpenDesc': 'Free availability without mandatory registration or barriers to query.',
    'terms.s4Title': 'Privacy & Free Access',
    'terms.s4Desc': 'We reiterate our commitment not to collect, store, or monetize personal information. Access to the catalog is free and transparent.',
  },
  QU: {
    // Navbar
    'nav.inicio': 'Qallariy',
    'nav.turismo': 'Puriy / Turismo',
    'nav.busquedaAvanzada': 'Tarpuy Maskay',
    'nav.buscar': 'Maskay',
    'nav.portalNacional': 'Piruw Suyupa Kichasqa Willakuy Llikan',
    'nav.selectLang': 'Simi / Idioma',

    // Search Modal
    'search.modalTitle': 'Piruwpa sumaq kayninkunata maskay',
    'search.placeholder': 'Llaqtapa sutinta, suyuta, kitiyta qillqay...',
    'search.popular': 'Aswan maskasqakuna:',
    'search.popular1': 'Machu Pikchu',
    'search.popular2': 'Titiqaqa Qucha',
    'search.popular3': 'Qullqa Wayq\'u',
    'search.popular4': 'Kuelap',
    'search.popular5': 'Wakachina',
    'search.pressEnter': 'Enter ñit\'iy llapa suyukunapi maskanapaq',
    'search.close': 'Wichqay',
    'search.exploreAll': 'Llapan tariykunata qhaway',

    // Home Page - Top Badge & Hero
    'hero.portalOpenData': 'KICHASQA WILLAKUY LLIKA',
    'hero.republicPeru': 'PIRUW MAMALLAQTA',
    'hero.title1': 'Piruw Suyupa Sumaq',
    'hero.titlePeru': 'Kawsayninta Riqsiy',
    'hero.subtitle': 'Kawsay pacha, ñawpa llaqtakuna, ñankuna riqsiy chaninchasqa willakuykunawan.',
    'hero.catNatural': 'Sallqa Kitiykuna',
    'hero.catCultural': 'Kultura Kawsay',
    'hero.catFolklore': 'Folclore',

    // Home Page - Metrics
    'home.totalResources': 'Llapan Kitiykuna',
    'home.inventoryNational': 'Mamallaqta Inventario',
    'home.naturalSites': 'Sallqa Pacha Kitiykuna',
    'home.cat1Natural': '1 Kaynin (Sallqa)',
    'home.culturalHeritage': 'Kultura Kawsay',
    'home.cat2Cultural': '2 Kaynin (Kultura)',
    'home.folkloreTraditions': 'Folclore & Ñawpa Kawsay',
    'home.cat3Folklore': '3 Kaynin (Folclore)',
    'home.metricAttractions': 'Sumaq Kitiykuna',
    'home.metricRegions': 'Suyukuna',
    'home.metricOpen': 'Kichasqa',

    // Home Page - Featured Catalog
    'home.featuredBadge': 'Mamallaqta Inventario • Akllasqa Kitiykuna',
    'home.featuredTitle': 'Aswan Riqsisqa Sumaq Kitiykuna',
    'home.featuredSubtitle': 'Chiqap willakuykunawan saywitiypi qillqasqa sumaq kitiykuna.',
    'home.viewAllCatalog': 'Llapan Catálogota Qhaway',
    'home.verifiedLocation': 'Chiqap Kiti',
    'home.viewTechnicalSheet': 'Técnica Fichata Qhaway',
    'home.viewFullDetail': 'Llapan willakuyta qhaway',

    // Home Page - Geoportal IDE
    'home.ideBadge': 'Pacha Willakuy Llika (IDE)',
    'home.geoportalTitle': 'Sumaq Kitiykunapa Geoportalnin',
    'home.geoportalSubtitle': 'WGS-84 coordenadaspi georreferenciachasqa kitiykunata mapapi qhaway.',
    'home.activeInGeoportal': 'Mapapi Kawsachkaq Registro',
    'home.category': 'Kaynin',
    'home.provinceDistrict': 'Provincia / Distrito',
    'home.latitude': 'Latitud (WGS-84)',
    'home.longitude': 'Longitud (WGS-84)',
    'home.selectMarkerMap': 'Saywitiypi huk kitita akllay willakuyninta qhawanaykipaq.',
    'home.viewFullTechSheet': 'Llapan Técnica Fichata Qhaway',

    // Home Page - Banner CTA
    'home.openDbBadge': 'Kichasqa Willakuy Base',
    'home.bannerTitle': 'Mamallaqtapa Turismo Catálogonta Maskay',
    'home.bannerDesc': 'Suyukuna, kitikuna, kayninkuna, ruraykunakama chaninchasqa chiqap willakuykunawan maskay.',
    'home.exploreCatalog': 'Catálogota Maskay',
    'home.viewGeoportal': 'Geoportalta Qhaway',
    'home.advantagesBadge': 'Llikapa Allin Kayninkuna',
    'home.whyChoose': 'Imaraykutaq',
    'home.whyChooseDesc': 'Piruw suyupi astawan allin, sumaq kichasqa willakuy qhawachiq kanchik. Riqsiqkunata, yachakuqkunata, puriqkunata mamallaqta willakuykunawan tinkuchinchik.',
    'home.feat1Title': '100% Kamachisqa Willakuy',
    'home.feat1Desc': 'Mamallaqta inventariomanta chiqap willakuykuna, fotokuna mana chinkaspa.',
    'home.feat2Title': 'Kichasqa & Waqaychasqa',
    'home.feat2Desc': 'Mana sutiykita churaspalla, mana qullqillapaq llapanta qhaway.',
    'home.feat3Title': 'Ñankuna & Purinakuna',
    'home.feat3Desc': 'Imaynata chayanaykipaq ñankuna, awtukuna, pachankunata willasunki.',
    'home.feat4Title': 'Yachaysapa Maskay',
    'home.feat4Desc': 'Suyukuna, kayninkuna, ruraykunakama utqaylla maskay.',
    'home.ctaTitle': '¿Piruwta Riqsiyta Munankichu?',
    'home.ctaDesc': 'OpenData llikapi 5,000 masnin sumaq kitiykunata, chiqap fotokunata, videokunata qhaway.',
    'home.ctaBtn': 'Kunan Qhaway',

    // Map
    'map.loading': 'OpenStreetMap Geoportalta kichachkan...',
    'map.loadingPapa': 'Geoportalta kichachkan...',

    // Turismo Page
    'turismo.badge': 'SUYUNTINPA CATALOGO • TURISMO INVENTARIO',
    'turismo.heroTitle': 'Piruw Suyupa',
    'turismo.heroHighlight': 'Sumaq Kitiyninkunata Riqsiy',
    'turismo.heroSubtitle': '2,290 masnin georreferenciachasqa sumaq kitiykunata, chiqap willakuykunata, ñankunata qhaway.',
    'turismo.title': 'Llapanchikpaq',
    'turismo.titleHighlight': 'Sumaq Kitiykuna',
    'turismo.subtitle': '5,000 masnin chaninchasqa kitiykunata llapa Piruw suyupi maskay.',
    'turismo.searchPlaceholder': 'Sutinta qillqay (kayhina: Machu Pikchu, Qullqa, Titiqaqa...)',
    'turismo.btnAdvanced': 'Yupikama (Código)',
    'turismo.btnSearch': 'Maskay',
    'turismo.filterRegion': 'Suyu / Departamento',
    'turismo.allRegions': 'Llapan suyukuna (25)',
    'turismo.filterCategory': 'Kaynin / Categoría',
    'turismo.allCategories': 'Llapan kayninkuna',
    'turismo.filterActivity': 'Ruray / Actividad',
    'turismo.allActivities': 'Llapan ruraykuna',
    'turismo.typesRegistered': 'qillqasqa layakuna',
    'turismo.official': 'Chiqap',
    'turismo.advancedTitle': 'Ficha Yupawan Maskay',
    'turismo.advancedPlaceholder': 'Ficha yupayta qillqay (kayhina: 62, 154, 820...)',
    'turismo.advancedDesc': 'Sapaq yupinwan chiqap kitiyta maskay.',
    'turismo.removeCode': 'Yupita pichay',
    'turismo.filtersApplied': 'Maskasqapi akllasqakuna',
    'turismo.filtersReady': 'Maskanapaq akllasqakuna',
    'turismo.filtersActive': 'Akllasqa layakuna:',
    'turismo.textFilter': 'Qillqa',
    'turismo.deptFilter': 'Suyu',
    'turismo.categoryFilter': 'Kaynin',
    'turismo.activityFilter': 'Ruray',
    'turismo.codeFilter': 'Ficha',
    'turismo.clearFilters': 'Llapanta pichay',
    'turismo.sectionBadge': 'Kichasqa Puriy',
    'turismo.allResources': 'Llapan Qillqasqa Sumaq Kitiykuna',
    'turismo.resourcesIn': 'Kitiykuna kay suyupi:',
    'turismo.codeSearch': 'Ficha Yupiy N°',
    'turismo.resultsFor': 'Tariy kaypaq:',
    'turismo.foundCount': 'sumaq kitiykuna tarisqa',
    'turismo.reset': 'Kutichiy',
    'turismo.loading': 'Willakuykunata maskachkan...',
    'turismo.noResults': 'Manam kitiykuna tarisqachu',
    'turismo.noResultsDesc': 'Huk suyuta akllay utaq maskasqaykita allichay.',
    'turismo.viewSheet': 'Sumaq kitipa fichanta qhaway',
    'turismo.inventory': 'Inventario',

    // Taytacha Leon XIVpa Ñannin Piruwpi
    'papa.badge': 'LLAPAN YUYAYKUNA • 11-16 NOVIEMBRE 2026',
    'papa.title': 'Taytacha',
    'papa.titleHighlight': 'León XIVpa Ñannin Piruwpi',
    'papa.subtitle': 'Taytacha León XIVpa llamkayninkuna, misa ruwayninkuna, runakunawan tinkiyninkuna suyukunapi.',
    'papa.searchPlaceholder': 'Maskay kitita utaq ruwayta (ej. Pimentel, Saqsaywaman, Monumental, Las Palmas...)',
    'papa.filterDept': 'Suyu',
    'papa.allDepts': 'Llapan suyukuna (6)',
    'papa.filterDate': 'Punchaw / Pacha',
    'papa.allDates': 'Llapan punchawkuna (6 punchaw)',
    'papa.filterType': 'Ruwaypa Niraqnin',
    'papa.allTypes': 'Llapan ruwaykuna',
    'papa.geoportalBadge': 'PACHA WILLAKUY LLIKA (IDE)',
    'papa.geoportalTitle': 'Taytachapa Ñanninpa Geoportalnin',
    'papa.geoportalDesc': 'Pacha mapapi qillqasqa ruwaykuna rikuy.',
    'papa.inspectorTitle': 'Akllasqa Ruwaypa Qhawaynin',
    'papa.deptActivities': '{dept} suyupi ruraykuna',
    'papa.allDeptActivities': 'Tukuy kamachisqa ruraykuna',
    'papa.selectToLocate': 'Huk ruraypi ñit\'iy saywitiypi qhawanaykipaq',
    'papa.itineraryTitle': 'Llapan Yuyaykuna & Horariokuna',
    'papa.officialSource': 'Gob.pe / IRTP Willakuy',
    'papa.activitiesFound': 'ruwaykuna tarisqa',
    'papa.viewOnMap': 'Mapapi qhawachiy',
    'papa.locatedOnMap': 'Mapapi kachkan',
    'papa.readOfficial': 'Gob.pe willakuyta ñawinchay',
    'papa.massTag': 'Hatun Santa Misa',
    'papa.youthTag': 'Waynakuna / Oración',
    'papa.pastoralTag': 'Pastoral Tinkiynin',
    'papa.travelTag': 'Phaway / Puriy',
    'papa.officialActivity': 'oficial ruray',
    'papa.officialActivities': 'oficial ruraykuna',
    'papa.november': 'Noviembre killapi, 2026',

    // Footer
    'footer.desc': 'Piruw suyupa sumaq kitiyninkuna qhawanapaq, kawsayninta riqsinapaq kichasqa willakuy llika.',
    'footer.connect': 'Ñuqaykuwan Tinkiy',
    'footer.nav': 'Navegación',
    'footer.navHome': 'Qallariy',
    'footer.navTurismo': 'Puriy / Turismo',
    'footer.navMap': 'Suyukunapa Mapan',
    'footer.navCatalog': 'Llapan Kitiykuna',
    'footer.dataApi': 'Kichasqa Willakuy & API',
    'footer.transparency': 'Sut\'i Kawsay',
    'footer.terms': 'Kamachikuykuna',
    'footer.privacy': 'Waqaychay Políticas',
    'footer.license': 'Kichasqa Licencia',
    'footer.claims': 'Reclamaciones Qillqa',
    'footer.faq': 'Tapukuykuna (FAQ)',
    'footer.rights': 'Piruw Suyupa Kichasqa Turismo Willakuynin',
    'footer.departments': '25 Suyukuna',
    'footer.resources': '2,290+ Kitiykuna',
    'footer.open': '100% Kichasqa',

    // Card
    'card.loadingPhoto': 'Chiqap fotota apamuspa...',
    'card.noPhoto': 'Mana fotoyuq chiqap fichapi',
    'card.recordNum': 'Ficha',
    'card.inventoryTitle': 'Mama Llaqtapa Turismo Inventario',
    'card.touristResource': 'Sumaq Kiti',
    'card.themeMuseum': 'Museum Wasikuna',
    'card.themeCultural': 'Kultura Kawsay',
    'card.themeWater': 'Qucha / Mayu Kawsay',
    'card.themeNature': 'Sallqa Pacha',
    'card.themeGeneral': 'Sumaq Kiti',

    // Ficha Detail Page
    'ficha.breadcrumbHome': 'Qallariy',
    'ficha.breadcrumbTurismo': 'Turismo',
    'ficha.backToCatalog': 'Kutiy Catálogoman',
    'ficha.sourceFile': 'Qallariy Ficha',
    'ficha.loading': 'Chiqap willakuykunata apamuspa...',
    'ficha.notFound': 'Kay fichaqa manam kanchu utaq inventariomanta pichasqam.',
    'ficha.notFoundDesc': 'Maskasqayki kitiqa manam inventariopi kanchu.',
    'ficha.exploreOther': 'Huk kitiykunata qhaway',
    'ficha.officialPhoto': 'Chiqap Foto',
    'ficha.officialGallery': 'Fotokuna Galeriyan',
    'ficha.photos': 'fotokuna',
    'ficha.officialDescription': 'Chiqap Sut\'inchay',
    'ficha.minceturInventory': 'Mamallaqta Inventario',
    'ficha.techSpecs': 'Ficha Técnica',
    'ficha.category': 'Kaynin:',
    'ficha.type': 'Niraq:',
    'ficha.subtype': 'Huch\'uy Niraq:',
    'ficha.altitude': 'Sayaynin:',
    'ficha.notSpecified': 'Mana willasqachu',
    'ficha.notSpecifiedMale': 'Mana willasqachu',
    'ficha.viewOnMap': 'Mapapi Qhaway',
    'ficha.seasonAndHours': 'Allin Pacha & Horariokuna',
    'ficha.visit': 'Watukuy',
    'ficha.recommendedSeason': 'Allin Pacha Watukunapaq',
    'ficha.visitingHours': 'Watukuna Horario',
    'ficha.recommendations': 'Kunaykuna',
    'ficha.activitiesInResource': 'Ruraykuna Kay Kitipi',
    'ficha.howToGet': 'Imaynata Chayana Ñan',
    'ficha.howToGetDesc': 'Chiqap ñankuna, awtukuna, tiempokunata willaspa.',
    'ficha.registeredSections': 'Tramos',
    'ficha.liveVideo': 'Chiqap Video',
    'ficha.additionalInfo': 'Inventariomanta Huk Willakuykuna',
    'ficha.section': 'Tramo',
    'ficha.fullscreen': 'Llapan pantalla qhaway',
    'ficha.share': 'Rikuchiy / Compartir',
    'ficha.copied': '¡Qillqasqaña!',

    // Pagination
    'pagination.showing': '{start}-manta {end}-kama qhawachkan, llapanqa {total} sumaq kitiykunamanta',
    'pagination.prev': 'Ñawpaq',
    'pagination.next': 'Qatiqnin',

    // Not Found
    'notFound.title': 'Manam tariykunachu',
    'notFound.desc': 'Maskasqayki p\'anqa utaq sumaq kiti manam kanchu utaq wakpi kachkan.',
    'notFound.btn': 'Sumaq Kitiykunata Maskay',

    // Privacy Page
    'privacy.title': 'Waqaychay Políticas',
    'privacy.badge': 'Waqaychasqa & Sut\'i Kawsay',
    'privacy.heroDesc': 'OpenData Piruwpi 100% qasi, mana sutiyuq, allin waqaychasqa kitiyta quykiku. Mamallaqtapa kichasqa willakuyninta qhawachiyllatam munayku.',
    'privacy.s1Title': 'Manam Runapa Sutinta Chaskikukuchu',
    'privacy.s1Box': 'Kay llikaqa MANAM mañakunchu, MANAM waqaychanchu, MANAM runapa willakuyninta huñunchu.',
    'privacy.s1Desc': 'Qasi qawayta atinki suyukunata, kayninkunata, mana qillqakuspa, mana sutiykita quspa.',
    'privacy.s2Title': 'Mamallaqtapa Chiqap Willakuynin',
    'privacy.s2Desc1': 'Llapan turismo willakuykunaqa Piruw Suyupa kichasqa willakuyninkunamantam hamun:',
    'privacy.s2Desc2': 'Sutikuna, willakuykuna, suyukuna, distritokuna, fotokunaqa sut\'i qhawachisqam kachkan, mana waqllichispa.',
    'privacy.s3Title': 'Munana: Aswan Allin Qillqa & Qhaway',
    'privacy.s3Desc': 'Kay portalqa musuq, utqaylla, allin llikatam qun runakunapaq, yachakuqkunapaqpas sumaqta qhawanankupaq.',
    'privacy.s4Title': 'Mana Qhatuypaq Qhawaychu',
    'privacy.s4Desc': 'Manam qhatuypaq qhawaykunata churanchischu. Llimphu, kichasqa willakuyllatam quykiku.',
    'privacy.backCatalog': 'Kutiy Turismo Catálogoman',

    // Terms Page
    'terms.title': 'Kamachikuykuna & Chaninchay',
    'terms.badge': 'Sut\'i Kawsay & Kichasqa Willakuy',
    'terms.heroDesc': 'OpenData Piruwqa mamallaqtapa kichasqa willakuyninta qhawachiq llikam, mana willakuyta cambiachispa.',
    'terms.s1Title': 'Chiqap Willakuypa Qallariynin',
    'terms.s1Desc1': 'Llapan willakuykuna, fichakuna, kodigokuna, fotokunaqa Piruw Suyupa kichasqa llikanmantam hamun.',
    'terms.s1Desc2': 'Piruw mamallaqtapa kamachiqkunam kay willakuykunapa dueñon kanku.',
    'terms.s2Title': 'Mana Waqllisqa Willakuy',
    'terms.s2Desc1': 'OpenData Piruwqa manam ima willakuytapas cambianchu nitaq pantachinchu.',
    'terms.s2Desc2': 'WGS-84 coordenadas nisqakunaqa chiqapmi waqaychakun.',
    'terms.s3Title': 'Munana: Aswan Allin Qhawana',
    'terms.s3Desc': 'Kay llikaqa runakunapaq, yachakuqkunapaq sumaqta qhawanankupaq ruwasqam:',
    'terms.featSearchTitle': 'Utqaylla Maskay',
    'terms.featSearchDesc': 'Suyuwan, kayninwan utaq kodigowan utqaylla maskay.',
    'terms.featDesignTitle': 'Sumaq Qillqakuna',
    'terms.featDesignDesc': 'Llimphu qhaway, yana hinaspa yuraq colorkunapi.',
    'terms.featOpenTitle': 'Kichasqa Yaykuna',
    'terms.featOpenDesc': 'Mana qillqakuspa librella yaykuna.',
    'terms.s4Title': 'Waqaychasqa & Qasi Yaykuy',
    'terms.s4Desc': 'Manam runapa sutinta nitaq willakuyninta waqaychankuchu. Qhawayqa 100% librem.',
  },
};

type TranslationKey = keyof typeof translations['ES'];

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey | string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'ES',
  setLanguage: () => {},
  t: (key: string) => key,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('ES');

  useEffect(() => {
    try {
      const savedLang = localStorage.getItem('opendata_lang') as Language;
      if (savedLang && ['ES', 'EN', 'QU'].includes(savedLang)) {
        setLanguageState(savedLang);
      }
    } catch {
      // ignore
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    try {
      localStorage.setItem('opendata_lang', lang);
    } catch {
      // ignore
    }
  };

  const t = (key: TranslationKey | string): string => {
    const langDict = translations[language] as Record<string, string>;
    if (langDict && langDict[key]) {
      return langDict[key];
    }
    const defaultDict = translations.ES as Record<string, string>;
    return defaultDict[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
